// This file is generated to provide the raw markdown content for the MatTableExt API page
// so callers can import it directly without using bundler loader syntax.

const mdLines: string[] = [
  '# Mat Table Ext',
  '',
  '### Directives',
  '',
  '#### `MatTableExt`',
  '',
  'Selector: `[mat-table-ext]`',
  '',
  'Exported as: `MatTableExt`',
  '',
  "##### **Properties**",
  '',
  '###### **Basic**',
  '',
  '| Name | Description |',
  '| :--- | :--- |',
  "| `@Input()`<br>`columns: MTExColumn[]` | The table's columns. |",
  "| `@Input()`<br>`dataSource: MatTableDataSource[]` | The table's data. |",
  "| `@Input()`<br>`loadingIdicator: boolean` | Whether the table's data is loading. Default is **`false`**. |",
  '',
  '###### **Page**',
  '',
  '| Name | Description |',
  '| :--- | :--- |',
  "| `@Input()`<br>`showPaginator: boolean` | Whether to show the paginator. Default is **`true`**. |",
  "| `@Input()`<br>`showFirstLastButtons: boolean` | Whether to show the first/last buttons UI to the user. Default is **`true`**. |",
  "| `@Input()`<br>`pageSizeOptions: number[]` | The set of provided page size options to display to the user. Default is **`[10, 50, 100]`** |",
  "| `@Output()`<br>`scroll : EventEmitter<any>` | The set of provided page size options to display to the user|",
  '',
  '###### **Sort**',
  '',
  '| Name | Description |',
  '| :--- | :--- |',
  "| `@Input()`<br>`sorting: boolean` | Sorting for table columns. Default is **`false`**. |",
  '',
  '###### **Expansion**',
  '',
  '| Name | Description |',
  '| :--- | :--- |',
  "| `@Input()`<br>`expandRows: boolean` | Whether the row is expandable. Default is **`false`**. |",
  "| `@Input()`<br>`expansionTemplateRef: TemplateRef<any>` | The template for the expandable row. |",
  "| `@Output()`<br>`expansionChange: EventEmitter<any>` | Event emitted when the user toggles the expandable row. |",
  '',
  '###### **Selection**',
  '',
  '| Name | Description |',
  '| :--- | :--- |',
  "| `@Input()`<br>`multiSelectable: boolean` | Whether to support multiple row selection. Default is **`true`**. |",
  "| `@Input()`<br>`rowSelection: boolean` | Whether the row is selectable. Default is **`false`**. |",
  "| `@Output()`<br>`selectionChanged: EventEmitter<any>` | Event emitted when the row is selected. |",
  '',
  '###### **Toolbar**',
  '',
  '| Name | Description |',
  '| :--- | :--- |',
  "| `@Input()`<br>`showToolbar: boolean` | Whether to show the toolbar. Default is **`false`**. |",
  "| `@Input()`<br>`toolbarTitle: string` | The text of the toolbar's title. Default is **`''`**. |",
  "| `@Input()`<br>`toolbarTemplate: TemplateRef<any>` | The template for the toolbar . |",
  '',
  '###### **Column**',
  '',
  '| Name | Description |',
  '| :--- | :--- |',
  "| `@Input()`<br>`columnHideable: boolean` | Whether the column is hideable. Default is **`false`**. |",
  "| `@Input()`<br>`columnPinnable: boolean` | Whether the column is pinnable. Default is **`false`**. |",
  "| `@Input()`<br>`columnGroups: MTExColumnGroup[]` | Column groups for grouped headers. Define groups with name, label, and columns. |",
  '',
  '###### **Row**',
  '',
  '| Name | Description |',
  '| :--- | :--- |',
  "| `@Input()`<br>`rowHover: boolean` | Whether to use the row hover style. Default is **`false`**. |",
  "| `@Input()`<br>`stripedRows: boolean` | Whether to use the row striped style. Default is **`false`**. |",
  "| `@Input()`<br>`enableRowPinning: boolean` | Whether to enable row pinning/freezing. Allows rows to be pinned at the top. Default is **`false`**. |",
  "| `@Input()`<br>`enableRowHiding: boolean` | Whether to enable row hiding feature. Default is **`false`**. |",
  '',
  '###### **Cell templates**',
  '',
  '| Name | Description |',
  '| :--- | :--- |',
  "| `@Input()`<br>`headerTemplateRef: TemplateRef<any>` | The header's cell template for the table. |",
  "| `@Input()`<br>`cellTemplateRef: TemplateRef<any>` | The cell template for the table. |",
  "| `@Input()`<br>`cellTemplateRefMap: TemplateRef<any>` | The cell template for the table when you want template for more columns. |",
  '',
  '### **Interfaces**',
  '',
  '#### `MTExColumn`',
  '',
  '```ts',
  'interface MTExColumn {',
  '  field: string;',
  '  header?: string;',
  '  name?: string;',
  '  type: MTExColumnType;',
  '  options?: string[];',
  '  footerText?: string;',
  '  headerTooltip?: TooltipProp;',
  '  cellTooltip?: TooltipProp;',
  '  disabled?: boolean;',
  "  pinned?: 'left' | 'right';",
  '  left?: string;',
  '  right?: string;',
  '  width?: string;',
  '  minWidth?: string;',
  '  maxWidth?: string;',
  '  resizable?: boolean;',
  '  tag?: MTExColumnTag;',
  '  cellTemplate?: TemplateRef<any> | null;',
  '  headerTemplate?: TemplateRef<any> | null;',
  '  showExpand?: boolean;',
  '  description?: string;',
  '  class?: string;',
  '  groupName?: string;',
  '}',
  '```',
  '',
  '#### `MTExColumnGroup`',
  '',
  'Column group definition for grouped headers.',
  '',
  '```ts',
  'interface MTExColumnGroup {',
  '  name: string;',
  '  label: string;',
  '  columns: string[];',
  '  colspan?: number;',
  '}',
  '```',
  '',
  '#### `MTExColumnSortProp`',
  '',
  'Column sort configuration properties.',
  '',
  '```ts',
  'interface MTExColumnSortProp {',
  "  arrowPosition?: 'before' | 'after';",
  '  disableClear?: boolean;',
  '  id?: string;',
  "  start?: 'asc' | 'desc';",
  '}',
  '```',
  '',
  '#### `MTExColumnTypeParameter`',
  '',
  'Column type parameter for formatting dates, currency, numbers, etc.',
  '',
  '```ts',
  'interface MTExColumnTypeParameter {',
  '  currencyCode?: string;',
  '  display?: string | boolean;',
  '  digitsInfo?: string;',
  '  format?: string;',
  '  locale?: string;',
  '  timezone?: string;',
  '}',
  '```',
  '',
  '#### `MTExColumnTag`',
  '',
  'Tag configuration for tag type columns.',
  '',
  '```ts',
  'interface MTExColumnTag {',
  '  [key: number]: MTExColumnTagValue;',
  '  [key: string]: MTExColumnTagValue;',
  '}',
  '```',
  '',
  '#### `MTExColumnTagValue`',
  '',
  'Tag value properties.',
  '',
  '```ts',
  'interface MTExColumnTagValue {',
  '  text?: string;',
  '  color?: string;',
  '}',
  '```',
  '',
  '#### `TooltipProp`',
  '',
  'Tooltip configuration properties.',
  '',
  '```ts',
  'interface TooltipProp {',
  '  value: string;',
  '  tooltipPosition?: TooltipPosition;',
  '}',
  '```',
  '',
  '#### `MTExPinnedTableConfig`',
  '',
  'Advanced configuration for row pinning feature.',
  '',
  '```ts',
  'interface MTExPinnedTableConfig {',
  '  enableRowPinning?: boolean;',
  '  pinnedTopTableMaxHeight?: string;',
  '  pinnedBottomTableMaxHeight?: string;',
  '  rowPinningFn?: RowPinningFunction;',
  '}',
  '```',
  '',
  '#### `MTExRowHidingConfig`',
  '',
  'Configuration for row hiding feature.',
  '',
  '```ts',
  'interface MTExRowHidingConfig {',
  '  enableRowHiding?: boolean;',
  '  hiddenRowIndices?: number[];',
  '  rowHidingFilterFn?: RowHidingFilterFunction;',
  '}',
  '```',
  '',
  '#### `MTExTableStyles`',
  '',
  'Table styling configuration.',
  '',
  '```ts',
  'interface MTExTableStyles {',
  '  tableHeight?: string;',
  '  tableWidth?: string;',
  '  toolbarHeight?: string;',
  '  tableClassName?: string;',
  '}',
  '```',
  '',
  '#### `MTExPDFConfig`',
  '',
  'PDF export configuration.',
  '',
  '```ts',
  'interface MTExPDFConfig {',
  "  pdfOrientation?: 'portrait' | 'landscape';",
  '}',
  '```',
  '',
  '#### Event Interfaces',
  '',
  '**`RowChange`**',
  '```ts',
  'interface RowChange {',
  '  row: { [key: string]: any };',
  '  index: number;',
  '}',
  '```',
  '',
  '**`RowSelectionChange`**',
  '```ts',
  'interface RowSelectionChange {',
  '  row: { [key: string]: any };',
  '  index: number;',
  '  isSelected: boolean;',
  '}',
  '```',
  '',
  '**`ExpansionChange`**',
  '```ts',
  'interface ExpansionChange {',
  '  data: { [key: string]: any };',
  '  index: number;',
  '  expanded: boolean;',
  '}',
  '```',
  '',
  '**`RowPinningChangeEvent`**',
  '```ts',
  'interface RowPinningChangeEvent {',
  '  row: any;',
  '  position: RowPinPosition;',
  '  index?: number;',
  '}',
  '```',
  '',
  '### Type aliases',
  '',
  '#### `MTExColumnType`',
  '',
  '```ts',
  "type MTExColumnType = 'selection' | 'string' | 'boolean' | 'number' | 'date' | 'datepicker' | 'textarea';",
  '```',
  '',
  '#### `MTExColumnPinValue`',
  '',
  '```ts',
  "type MTExColumnPinValue = 'left' | 'right' | null;",
  '```',
  '',
  '#### `TooltipPosition`',
  '',
  '```ts',
  "type TooltipPosition = 'left' | 'right' | 'above' | 'below' | 'before' | 'after';",
  '```',
  '',
  '#### `RowPinPosition`',
  '',
  '```ts',
  "type RowPinPosition = 'top' | 'bottom' | null;",
  '```',
  '',
  '#### `RowPinningFunction`',
  '',
  '```ts',
  'type RowPinningFunction = (row: any, index: number) => RowPinPosition;',
  '```',
  '',
  '#### `RowHidingFilterFunction`',
  '',
  '```ts',
  'type RowHidingFilterFunction = (row: any, index: number) => boolean;',
  '```',
  ''
];

const md = mdLines.join('\n');

export default md;
